In [68]:
import numpy as np

In [71]:
u = np.array([1,2,3,4,5])
v = np.array([1,2,3,4, 5])
u + v

array([ 2,  4,  6,  8, 10])

In [72]:
u * v

array([ 1,  4,  9, 16, 25])

In [76]:
def vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return result
    

In [77]:
vector_multiplication(u, v)

np.float64(55.0)

In [78]:
u.dot(v)

np.int64(55)

In [81]:
u.shape

(5,)

In [95]:
U = np.array([[2,4,5,6],[1,2,1,2],[3,1,2,1]])
V = np.array([1,0.5,2,1])

def matric_vector_multiplication (U, V):
    assert U.shape[1] == V.shape[0]
    num_row = U.shape[0]
    result = np.zeros(num_row)
    for i in range(num_row):
        result[i] = vector_multiplication(U[i], V)
    return result



In [96]:
matric_vector_multiplication(U, V)

array([20. ,  6. ,  8.5])

In [97]:
U.dot(V)


array([20. ,  6. ,  8.5])