In [1]:
import numpy as np

In [3]:
zero_numpy = np.zeros(15)
zero_numpy

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
one_numpy = np.ones(10)
one_numpy

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10,16)

array([16, 16, 16, 16, 16, 16, 16, 16, 16, 16])

In [8]:
my_list = [5,4,3,2,1]
list_to_numpy = np.array(my_list)
list_to_numpy

array([5, 4, 3, 2, 1])

In [12]:
np.arange(21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [16]:
np.linspace(1,21,5)

array([ 1.,  6., 11., 16., 21.])

In [19]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [20]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [21]:
np.ones((3))

array([1., 1., 1.])

In [23]:
np.full((10,2), 2)

array([[2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2]])

In [26]:
arr= np.array([[2, 3, 4],[4,5,6]])
first_row = arr[0]
first_row

array([2, 3, 4])

In [28]:
first_col = arr[:, 0]
first_col

array([2, 4])

In [29]:
# negative randomness
np.random.randn(5,2)

array([[ 1.65724653, -0.43450892],
       [-1.01559634,  2.13286837],
       [-2.07315592,  0.56960832],
       [-1.16231114,  0.32915956],
       [-2.0182202 , -1.98425457]])

In [31]:
# positive randomess
np.random.rand(5,2)

array([[0.79902773, 0.25009107],
       [0.22627081, 0.39046772],
       [0.76296283, 0.78888867],
       [0.94206119, 0.17947795],
       [0.37909887, 0.77035782]])

In [39]:
np.random.seed(6)
random_array = np.random.rand(5, 2)  # Generates random numbers between 0 and 1
random_array

array([[0.89286015, 0.33197981],
       [0.82122912, 0.04169663],
       [0.10765668, 0.59505206],
       [0.52981736, 0.41880743],
       [0.33540785, 0.62251943]])

In [44]:
np.random.seed(6)
np.random.randint(low = 1, high = 100, size = (5,2))

array([[11, 74],
       [85, 80],
       [81, 63],
       [26,  2],
       [76, 78]], dtype=int32)

In [50]:
arrplus = arr + 1
arrplus

array([[3, 4, 5],
       [5, 6, 7]])

In [52]:
arrplus + 1

array([[4, 5, 6],
       [6, 7, 8]])

In [53]:
arrmul = arrplus * 5
arrmul

array([[15, 20, 25],
       [25, 30, 35]])

In [54]:
arr1 = np.ones(4)
arr2 = np.full(4, 3)
result = arr1 + arr2  # Element-wise addition
result1 = arr1 / arr2  # Element-wise division

In [55]:
result

array([4., 4., 4., 4.])

In [56]:
result1

array([0.33333333, 0.33333333, 0.33333333, 0.33333333])

In [62]:
arr = np.array([1, 2, 3, 4])
greater_less_5 = arr < 5 

In [63]:
greater_less_5

array([ True,  True,  True,  True])

In [64]:
arr[arr > 2]

array([3, 4])

In [66]:
arr.min()

np.int64(1)

In [67]:
arr.mean()

np.float64(2.5)